version: 2.1
orbs:
  maven: circleci/maven@1.4.1
executors:
  java17:
    docker:
      - image: cimg/openjdk:17.0
jobs:
  build:
    executor: java17
    steps:
      - checkout
      - maven/install
      - maven/test
